GRENADE BOX + MINOR WORD CHANGE ON CARGO COMPUTER
mattmatterson111/IS12-Warfare-Two pull request #1
Opened 2024-08-05 22:05 UTC by stuff-labs

**FEATURES**
- A deployable grenade box, allowing easy transport of grenades to and from the front.

- A minor change for one piece of cargo computer loc, which referenced Rpframework.

**POTENTIAL ISSUES**
- Grenade selection isn't precise. When you try and remove a grenade it'll randomly pick from the list of stored grenades. While I don't foresee people carrying boxes with 80 different type of grenades, it could become a minor QOL issue if people consistently carry around boxes that are a mix of frags and smokes. If you really want to avoid this issue I can quickly code in a way of selecting a specific stored grenade via altclick if need be.

- Pre-Set grenade boxes require code like this to spawn with grenades you can actually take out.
`	grenades = list(new /obj/item/grenade/frag)` 
While not bad for crates with singular grenades, it does lead to quite long lists if you want a pre-made crate with the full amount of 5 grenades.

2024-08-05 22:43 UTC, mattmatterson111 requested changes

2024-08-05 22:43 UTC, mattmatterson111 commented on code/game/objects/items/grenade_box.dm
> +/obj/item/grenade_box/proc/update_sprite() //Updating the sprite to reflect the amount of grenades within
A proc for this exists already it's called `update_icon()`. Please don't make a new proc.

2024-08-05 22:43 UTC, mattmatterson111 commented on code/game/objects/items/grenade_box.dm
> +/obj/item/grenade_box/RightClick(mob/user) //Opening and closing
You need a "can interact" check here. Right click will always function at any distance otherwise. Especially since you are not calling the parent.

2024-08-05 22:43 UTC, mattmatterson111 commented on code/game/objects/items/grenade_box.dm
> +	if(open == FALSE)
`!open`

2024-08-05 22:43 UTC, mattmatterson111 commented on code/game/objects/items/grenade_box.dm
> +		G.loc = src
Use forcemove.

2024-08-05 22:43 UTC, mattmatterson111 commented on code/game/objects/items/grenade_box.dm
> +	if(grenades.len == 0)
`!grenades.len`

2024-08-05 22:43 UTC, mattmatterson111 commented on code/modules/placeholder/placeholder.dm
> +	name = "R.E.D Cargo Machine"
R.E.D. is correct grammar wise.

2024-08-05 22:43 UTC, mattmatterson111 commented on code/game/objects/items/grenade_box.dm
> +		var/removal_target = pick(grenades)
Why pick? If I insert a grenade then the one I get out will always be random?

2024-08-05 22:43 UTC, mattmatterson111 commented on code/game/objects/items/grenade_box.dm
> +	if(open == TRUE)
`if(open)`

2024-08-05 22:43 UTC, mattmatterson111 commented on code/game/objects/items/grenade_box.dm
> +			update_sprite()
call `update_icon()` here.

2024-08-05 23:29 UTC, stuff-labs commented
![OIP (10)](https://github.com/user-attachments/assets/42438e6b-dfb1-409b-9d54-0d77df3de937)
I called my uncle (pictured above) and he should have resolved most issues

2024-08-06 14:47 UTC, mattmatterson111 commented
LGTM

2024-08-06 14:47 UTC, merged